theme: minima
title: Home
author: "Digital Preservation Southampton"
email: digitalpreservation@soton.ac.uk
github_username: Southampton-Digital-Humanities
description: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  show_excerpts: true
  nav_pages:
    - contributors.md
